# Generated by Django 5.2.6 on 2025-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=30, help_text='Duración del servicio en minutos'),
        ),
    ]
