# Generated by Django 5.2.6 on 2025-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_servicio',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
