# Generated by Django 5.2.6 on 2025-10-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cita_duracion_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbero',
            options={'ordering': ['usuario__first_name'], 'verbose_name': 'Barbero', 'verbose_name_plural': 'Barberos'},
        ),
    ]
