# Generated by Django 5.2.6 on 2025-10-13 05:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_barbero_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
    ]
