# Generated by Django 5.2.6 on 2025-10-14 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_barbero_foto'),
        ('servicios', '0003_alter_servicio_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='reservas.disponibilidad'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada'])), fields=('disponibilidad',), name='unique_disponibilidad_activa'),
        ),
    ]
